[package]
name = "smart-pointer"
version = "0.1.0"
authors = ["nakamura_tatsu <nakamura_tatsu@atlas-is.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
